name: main  #nazwa
on:
  push:
    branches:
      - main  #wykona sie tylko kiedy push na main
jobs:
  test:
    runs-on: ${{ matrix.os }}  #uruchamiane na obu systemach operacyjnych
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        python-version: ["3.9", "3.10", "3.11"]  #testowane wersje pythona
        exclude:  #wylaczenie wersji pythona 3.10 na systemie ubuntu
          - os: ubuntu-latest
            python-version: "3.10"

    steps:
      - name: Set up Python  #konfiguracja srodowiska
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Update pip  #aktualizacja pip
        run: |
          python -m pip install --upgrade pip

      - name: Install flake8  #instalacja flake8
        run: |
          python -m pip install flake8
        #unittest jest w standardowej bibliotece pythona, nie wymaga instalacji
        
      - name: Display Python version  #wyswietlenie aktualnej wersji pythona
        run: python --version

      - name: Run flake8  #uruchomienie flake8
        run: flake8

      - name: Run unittest  #uruchomienie unittest dla plikow *.py
        run: python -m unittest discover -s . -p '*.py'
